### ISSUE TITLE
dashboard启动报错 rgw-builtin-plugins.json

### ISSUE THREAD

**Issue by root123456** [tmzk1005/reactor-gateway#1]
![image](https://github.com/tmzk1005/reactor-gateway/assets/16095234/68422a75-4c8b-4c10-a89b-8782618f1632)
请问一下rgw-builtin-plugins.json在哪能获取？

**Comment by tmzk1005** [comment]
执行gradle task  `./gradlew :dashboard:generateBuiltinPluginsInfo` 自动生成的。

**Comment by tmzk1005** [comment]
这个文件没有打到jar包里， 我修复下。
